categories = {
    "fuel": {"attributes": ["fuel_type", "volume_l"],},
    "baby_food": {"attributes": ["baby_food_exp_date", "baby_food_weight_g"],},
    "canned_food": {"attributes": ["canned_food_exp_date", "canned_food_weight_g"],},
    "dry_food": {"attributes": ["dry_food_exp_date", "dry_food_weight_g"],},
    "water": {"attributes": ["water_exp_date", "water_volume_ml"],},
    "heavy_equipment": {"attributes": ["he_type"],},
    "ice": {"attributes": ["ice_weight_kg"]},
    "battery": {"attributes": ["battery_type", "battery_voltage"],},
    "power_generator": {"attributes": ["pg_watts", "pg_fuel_type"],},
    "tool": {"attributes": ["tool_material", "tool_color", "tool_weight_kg"],},
    "medical_device": {"attributes": ["md_type"],},
    "clothing": {"attributes": ["clothing_type", "clothing_gender", "clothing_size"],},
    "medication": {"attributes": ["medication_exp_date"]},
}
